### ISSUE TITLE
Windows Wheel Builds

### ISSUE THREAD

**Issue by zallsjsksk** [alanpq/lol-blender#2]
Command '['F:\\Program Files\\Blender Foundation\\Blender 4.2\\4.2\\python\\bin\\python.exe', '-m', 'pip', 'install', '--force-reinstall', 'X:\\Documents\\Projects\\lol-blender\\bindings\\target\\wheels\\league_toolkit-0.1.0-cp311-none-win_amd64.whl']' returned non-zero exit status 1.

**Comment by zallsjsksk** [comment]
Blender 4.2

**Comment by alanpq** [comment]
Until I add automatic downloading of the wheel to the addon, you'll need to download the correct .whl for your OS/architecture from the [latest release](https://github.com/alanpq/lol-blender/releases/latest). Then, in the addon preferences you point the "Wheel Path" to that .whl.

![wheel path preferences screenshot](https://github.com/user-attachments/assets/8e91bde8-7e98-411a-aa7f-71d1794c59e5)
(ignore "Library Path")

Currently, the Github Action only builds Linux wheels, so if you're on Windows/OSX, you'll have to either wait for me to update the action, or build the wheel yourself.

**Comment by zallsjsksk** [comment]
I am using Windows OS Waiting for you to update

**Comment by alanpq** [comment]
I've pushed a pre-release with the Windows whl's - can you check if that works for you? I can't easily test Windows at the moment.

**Comment by zallsjsksk** [comment]
ok thx

**Comment by zallsjsksk** [comment]
bpy.ops.example.install_dependencies()

**Comment by zallsjsksk** [comment]
![Uploading 屏幕截图 2024-08-17 015558.png…]()

**Comment by zallsjsksk** [comment]
![屏幕截图 2024-08-17 015613](https://github.com/user-attachments/assets/e001968e-7cb3-4bbe-8bc2-fdc1c2b565c8)

**Comment by zallsjsksk** [comment]
![屏幕截图 2024-08-17 015558](https://github.com/user-attachments/assets/00954b78-6515-4498-bb2f-c08ce80481c9)

no Import

**Comment by alanpq** [comment]
Import isn't implemented yet (I had it wrong in the README sorry!). Export is also only accessible through the panel in the 3D viewport (will be changed soon)

**Comment by alanpq** [comment]
Closing since #7
